expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense
from .views import ExpenseListView, CategoryListView, CategoryCreateView, \
    CategoryUpdateView, CategoryDeleteView

urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list')
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list')
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
             model=Expense,
             success_url=reverse_lazy('expenses:expense-list')
         ),
         name='expense-delete'),

    path('expense/categories/', CategoryListView.as_view(), name='categories'),
    path('expense/category_add/', CategoryCreateView.as_view(), name='category_add'),
    path('expense/category_update/<int:pk>/',
         CategoryUpdateView.as_view(), name='category_update'),
    path('expense/category_dalete/<int:pk>/',
         CategoryDeleteView.as_view(), name='category_delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')
         ),
]

expenses/models.py
import datetime

from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')
    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
import datetime

from django import forms
from django.forms import CheckboxSelectMultiple

from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    GROPING = ('date+', 'date-', 'category+', 'category-', )
    SORT = ('date+', 'date-', 'category+', 'category-', )
    grouping = forms.ChoiceField(choices=[('', '')] + list(zip(GROPING, GROPING)))
    sorting = forms.ChoiceField(choices=[('', '')] + list(zip(GROPING, GROPING)))
    years = range(2000, datetime.date.today().year + 1)
    start_date = forms.DateField(widget=forms.SelectDateWidget(years=years),
                                 required=False)
    end_date = forms.DateField(widget=forms.SelectDateWidget(years=years),
                               required=False)

    category = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Category.objects.all(),
        widget=CheckboxSelectMultiple(),
    )

    class Meta:
        model = Expense
        fields = ('name', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i in self.fields:
            self.fields[i].required = False


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

expenses/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm, CategoryEditForm
from .models import Expense, Category
from .reports import summary_per_category, summary_per_year_month, \
    total_amount, total_for_categories


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)

        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            if name:
                queryset = queryset.filter(name__icontains=name)

            categories = form.cleaned_data['category']
            if categories:
                filter_category = Q()
                for category in categories:
                    filter_category |= Q(category=category.id)
                queryset = queryset.filter(filter_category)

            grouping = form.cleaned_data['grouping']
            if grouping == 'date+' or grouping == 'date-':
                if grouping[-1] == '+':
                    queryset = queryset.order_by(grouping[:-1])
                elif grouping[-1] == '-':
                    queryset = queryset.order_by(f'-{grouping[:-1]}')
            elif grouping == 'category+' or grouping == 'category-':
                if grouping[-1] == '+':
                    queryset = queryset.order_by(f'{grouping[:-1]}__name')
                elif grouping[-1] == '-':
                    queryset = queryset.order_by(f'-{grouping[:-1]}__name')

            sorting = form.cleaned_data['sorting']
            if sorting == 'date+' or sorting == 'date-':
                if sorting[-1] == '+':
                    queryset = queryset.order_by(sorting[:-1])
                elif sorting[-1] == '-':
                    queryset = queryset.order_by(f'-{sorting[:-1]}')
            elif sorting == 'category+' or sorting == 'category-':
                if sorting[-1] == '+':
                    queryset = queryset.order_by(f'{sorting[:-1]}__name')
                elif sorting[-1] == '-':
                    queryset = queryset.order_by(f'-{sorting[:-1]}__name')

            start_date = form.cleaned_data['start_date']
            if start_date:
                queryset = queryset.filter(date__gte=start_date)

            end_date = form.cleaned_data['end_date']
            if end_date:
                queryset = queryset.filter(date__lte=end_date)

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            summary_per_year_month=summary_per_year_month(queryset),
            amount=total_amount(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    template_name = 'expenses/category_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = Expense.objects.all()
        categories = self.model.objects.all()
        return super().get_context_data(
            expenses=total_for_categories(categories, queryset),
        )


class CategoryCreateView(CreateView):
    model = Category
    template_name = 'expenses/category_create.html'
    success_url = reverse_lazy('expenses:expense-list')
    form_class = CategoryEditForm


class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'expenses/category_create.html'
    success_url = reverse_lazy('expenses:categories')
    form_class = CategoryEditForm


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'expenses/expense_confirm_delete.html'
    success_url = reverse_lazy('expenses:categories')

expenses/templates/expenses/category_create.html
{% extends "base.html" %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">save</button>
    </form>

    <a href="{% url 'expenses:expense-list' %}">На главную</a>
{% endblock %}

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
    <table border="1">
        <thead>
        <tr>
            <th>category</th>
            <th>expense</th>
        </tr>
        </thead>

        <tbody>
        {% for k, v in expenses.items %}
            <tr>
                <td>
                    {{ k }}
                    {% for _, val in v.items %}</td>
                        <td>
                            {{ val|floatformat:2 }}
                        </td>
                        <td><a href="{% url 'expenses:category_update' k.id %}">edit</a></td>
                        <td><a href="{% url 'expenses:category_delete' k.id %}">delete</a></td>
                        </tr>
                    {% endfor %}
        {% endfor %}

        </tbody>
    </table>

    <a href="{% url 'expenses:expense-list' %}">На главную</a>
{% endblock %}

expenses/templates/expenses/expense_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
    <a href="{% url 'expenses:categories' %}">Cancel</a>
</form>

{% endblock %}

expenses/templates/expenses/expense_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'expenses:expense-create' %}">add a note</a>
    <a href="{% url 'expenses:categories' %}">categories</a>
    <a href="{% url 'expenses:category_add' %}">add category</a>

    <form method="get" action="">
        {{ form.as_p }}
        <button type="submit">search</button>
    </form>
    <br>
    <table border="1">
        {% if form.cleaned_data.grouping == "date+" or form.cleaned_data.grouping == "date-" %}
            <thead>
            <tr>
                <th>no.</th>
                <th>category</th>
                <th>description</th>
                <th>amount</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in object_list %}
                {% ifchanged obj.date %}
                    <tr>
                        <td colspan="4">{{ obj.date }}</td>
                    </tr>
                {% endifchanged %}
                <tr>
                    <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
                    <td>{{ obj.category|default:"-" }}</td>
                    <td>{{ obj.name|default:"-" }}</td>
                    <td>{{ obj.amount|floatformat:2 }}</td>
                    <td>
                        <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
                        <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">no items</td>
                </tr>
            {% endfor %}
            </tbody>



        {% elif form.cleaned_data.grouping == "category+" or form.cleaned_data.grouping == "category-" %}
            <thead>
            <tr>
                <th>no.</th>
                <th>date</th>
                <th>description</th>
                <th>amount</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in object_list %}
                {% ifchanged obj.category %}
                    <tr>
                        <td colspan="4">{{ obj.category }}</td>
                    </tr>
                {% endifchanged %}
                <tr>
                    <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
                    <td>{{ obj.date|default:"-" }}</td>
                    <td>{{ obj.name|default:"-" }}</td>
                    <td>{{ obj.amount|floatformat:2 }}</td>
                    <td>
                        <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
                        <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">no items</td>
                </tr>
            {% endfor %}
            </tbody>



        {% else %}
            <thead>
            <tr>
                <th>no.</th>
                <th>category</th>
                <th>description</th>
                <th>date</th>
                <th>amount</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in object_list %}
                <tr>
                    <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
                    <td>{{ obj.category|default:"-" }}</td>
                    <td>{{ obj.name|default:"-" }}</td>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.amount|floatformat:2 }}</td>
                    <td>
                        <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
                        <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="6">no items</td>
                </tr>
            {% endfor %}
            </tbody>
        {% endif %}
    </table>

    {% include "_pagination.html" %}
    <hr>
    <table border="1">
        <caption>Summary per category</caption>
        <tr>
            {% for category, total in summary_per_category.items %}
                <td>{{ category }}: {{ total|floatformat:2 }}</td>{% endfor %}
        </tr>
    </table>
    <hr>
    <table border="1">
        <caption>Summary per year/month</caption>
        <tr>
            {% for year_month, total in summary_per_year_month.items %}
                <td>{{ year_month|date:"Y-m" }}: {{ total|floatformat:2 }}</td>{% endfor %}
        </tr>
    </table>
    <hr>
    <table border="1">
        <caption>Total amount</caption>
        <tr>
            {% for _, total in amount.items %}
                <td>Total: {{ total|floatformat:2 }}</td>{% endfor %}
        </tr>
    </table>

{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>